WebApplication/Controllers/MSupplyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
namespace WebApplication.Controllers
{
    [OrAuthorization(Roles = "Admin")]
    public class MSupplyController : Controller
    {
        // GET: MSupply
        JordanEntities db = new JordanEntities();
        public ActionResult Index()
        {
            if (Session["Admin"] != null)
            {
                return View(db.Supplies.ToList());
            }
            return RedirectToAction("Login", "HomeAdmin");
        }
        public ActionResult Details(int id)
        {

            if (Session["Admin"] != null)
            {
                if (id == null)
                {

                    return RedirectToAction("PageError", "HomeAdmin");
                }
                Supply supply = db.Supplies.Find(id);
                if (supply == null)
                {
                    return RedirectToAction("PageError", "HomeAdmin");
                }
                return View(supply);
            }
            return RedirectToAction("Login", "HomeAdmin");
        }

        public ActionResult Create()
        {
            if (Session["Admin"] != null)
            {
                return View();
            }
            return RedirectToAction("Login", "HomeAdmin");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Supply_Name,Supply_Address")] Supply supply)
        {
            if (ModelState.IsValid)
            {
                db.Supplies.Add(supply);
                var result = db.SaveChanges();
                if (result > 0)
                {
                    TempData["CreateSupply"] = "Create supply successful.";
                }
                return RedirectToAction("Index");
            }

            return View(supply);
        }

        public ActionResult Edit(int id)
        {
            if (Session["Admin"] != null)
            {
                if (id == null)
                {
                    return RedirectToAction("PageError", "HomeAdmin");
                }
                Supply supply = db.Supplies.Find(id);
                if (supply == null)
                {
                    return RedirectToAction("PageError", "HomeAdmin");
                }
                return View(supply);
            }
            return RedirectToAction("Login", "HomeAdmin");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Supply_ID,Supply_Name,Supply_Address")] Supply supply)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supply).State = EntityState.Modified;
               var result= db.SaveChanges();
                if (result > 0)
                {
                    TempData["EditSupply"] = "Edit supply successful.";
                }
                return RedirectToAction("Index");
            }
            return View(supply);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["Admin"] != null)
            {
                if (id == null)
                {
                    return RedirectToAction("PageError", "HomeAdmin");
                }
                Supply supply = db.Supplies.Find(id);
                if (supply == null)
                {
                    return RedirectToAction("PageError", "HomeAdmin");
                }
                return View(supply);
            }
            return RedirectToAction("Login", "HomeAdmin");
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Supply supply = db.Supplies.Find(id);
                db.Supplies.Remove(supply);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                TempData["ErrorDeleteSupply"] = "Cannot delete this supply.";
                return RedirectToAction("Index");
            }
        }
    }
}

WebApplication/Views/MSupply/Create.cshtml
@model WebApplication.Models.Supply

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Create</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/HomeAdmin">Home</a></li>
                    <li><a href="/MCategory/Index">Supply Management</a></li>
                    <li><span>Create</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="~/Theme/assets/images/author/avatar.png" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">Welcome: @Session["Admin"]<i class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Logout","HomeAdmin")">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="col-12 mt-5">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Create A New Supply Form</h4>

                @using (Html.BeginForm("Create", "MSupply", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @Html.HiddenFor(model => model.Supply_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supply_ID, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Supply_Name, "Supply Name", htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Supply_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Supply_Name, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Supply_Address, "Supply Address", htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Supply_Address, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.Supply_Address, "", new { @class = "text-danger" })
                </div>

                <div>
                    <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Create</button> &nbsp;
                    <a href="/MSupply" class="btn btn-info mt-4 pr-4 pl-4">
                        Back to List
                    </a>
                </div>
            </div>
                }

            </div>
        </div>
    </div>
</div>

WebApplication/Views/MSupply/Delete.cshtml
@model WebApplication.Models.Supply

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Delete</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/HomeAdmin">Home</a></li>
                    <li><a href="/MSupply/Index">Supply Management</a></li>
                    <li><span>Delete</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="~/Theme/assets/images/author/avatar.png" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">Welcome: @Session["Admin"]<i class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Logout","HomeAdmin")">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="col-12 mt-5">
        <div class="card">
            <div class="card-body">
                <h4>Are you sure you want to delete this item?</h4>
                <br />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.LabelFor(model => model.Supply_Name, "Supply Name"): &nbsp;
                        <span style="font-weight:normal">@Html.DisplayFor(model => model.Supply_Name)</span>
                    </dt>

                </dl>

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-primary  mt-4 pr-4 pl-4" /> &nbsp;
                        <a href="/MSupply" class="btn btn-info  mt-4 pr-4 pl-4">
                            Back to List
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

WebApplication/Views/MSupply/Details.cshtml
@model WebApplication.Models.Supply

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<h2>Supply Details</h2>

<div>
 
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.Supply_Name, "Supply Name"): &nbsp;<span style="font-weight:normal">@Html.DisplayFor(model => model.Supply_Name)</span>
        </dt>
        <dt>
            @Html.LabelFor(model => model.Supply_Address, "Supply Address"): &nbsp;<span style="font-weight:normal">@Html.DisplayFor(model => model.Supply_Address)</span>
        </dt>

    </dl>
</div>
<p>
    <a href="/MSupply/Edit/@Model.Supply_ID" class="btn btn-info">
        Edit
    </a>
    &nbsp;
    <a href="/MSupply" class="btn btn-info">
        Back to List
    </a>
</p>

WebApplication/Views/MSupply/Edit.cshtml
@model WebApplication.Models.Supply

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Edit</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/HomeAdmin">Home</a></li>
                    <li><a href="/MSupply/Index">Supply Management</a></li>
                    <li><span>Edit</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="~/Theme/assets/images/author/avatar.png" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">Welcome: @Session["Admin"]<i class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Logout","HomeAdmin")">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="col-12 mt-5">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">Edit Supply Form</h4>
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Supply_ID)


            <form>
                <div class="form-group">
                    @Html.LabelFor(model => model.Supply_Name, "Supply Name", htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Supply_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Supply_Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Supply_Address, "Supply Address", htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Supply_Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Supply_Address, "", new { @class = "text-danger" })
                </div>
                <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Save</button>
                <a href="/MSupply" class="btn btn-info  mt-4 pr-4 pl-4">
                    Back to List
                </a>
            </form>
                }
            </div>
        </div>
    </div>
</div>

WebApplication/Views/MSupply/Index.cshtml
@model IEnumerable<WebApplication.Models.Supply>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@if (TempData["ErrorDeleteSupply"] != null)
{

    <div class="form-group">
        <br />
        <div class="col-md-3">
            <div class="alert alert-danger" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong> @TempData["ErrorDeleteSupply"]</strong>

            </div>

        </div>
    </div>
}
@if (TempData["EditSupply"] != null)
{

    <div class="form-group"><br />
        <div class="col-md-3">
            <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong> @TempData["EditSupply"]</strong>

            </div>

        </div>
    </div>
}
@if (TempData["CreateSupply"] != null)
{

    <div class="form-group"><br />
        <div class="col-md-3">
            <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong> @TempData["CreateSupply"]</strong>

            </div>

        </div>
    </div>
}
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Supply Management</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/HomeAdmin">Home</a></li>
                    <li><span>Supply Management</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="~/Theme/assets/images/author/avatar.png" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">Welcome: @Session["Admin"]<i class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Logout","HomeAdmin")">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row mt-5 mb-5">
        <div class="col-12">
            <div class="card">
                <div class="col-12 mt-5">
                    <div class="card">

                        <a href="/MSupply/Create" class="btn btn-outline btn-primary " style="font-size:20px; width:10%">Create</a>
                        <div class="card-body">
                            <h4 class="header-title">Supply Table</h4>
                            <div class="single-table">
                                <div class="table-responsive">
                                    <table class="table table-hover progress-table text-center">
                                        <thead class="text-uppercase">
                                            <tr>
                                                <th scope="col">ID</th>
                                                <th scope="col">Supply Name</th>
                                                <th scope="col">action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <th scope="row"> @Html.DisplayFor(modelItem => item.Supply_Name)</th>
                                                    <td> @Html.DisplayFor(modelItem => item.Supply_Address)</td>
                                                    <td>
                                                        <ul class="d-flex justify-content-center">
                                                            <li class="mr-3"><a href="/MSupply/Edit/@item.Supply_ID" class="text-secondary"><i class="fa fa-edit"></i></a></li>
                                                            <li><a href="/MSupply/Delete/@item.Supply_ID" class="text-danger"><i class="ti-trash"></i></a></li>
                                                        </ul>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Progress Table end -->
            </div>
        </div>
    </div>
</div>

<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(2500, 0).slideUp(500, function () {
            $(this).hide();
        });
    }, 1000);
</script>