WebApplication/Controllers/MReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;
using System.Data.Entity;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using OfficeOpenXml;

namespace WebApplication.Controllers
{
    [OrAuthorization(Roles = "Admin")]
    
    public class MReportController : Controller
    {
        JordanEntities db = new JordanEntities();
        // GET: MReport
        public ActionResult Index()
        {
            if (Session["Admin"] != null)
            {
                var od = db.OrderDetails;
               
                var order = db.OrderDetails.Include(x => x.Product).Include(x => x.Order).ToList();
                return View(order.Where(x => x.Order.Order_Date.Date == DateTime.Now.Date).ToList());
                }
            return RedirectToAction("Login", "HomeAdmin");
        }
        public ActionResult FromDate(DateTime? datefrom)
        {
            if (Session["Admin"] != null)
            {
                var od = db.OrderDetails;

                var order = db.OrderDetails.Include(x => x.Product).Include(x => x.Order).ToList();
                Session["FromDate"] = datefrom;
                return View(order.Where(x => x.Order.Order_Date.Date == datefrom).ToList());
            }
            return RedirectToAction("Login", "HomeAdmin");
        }
        public ActionResult DateRange(DateTime? datefrom, DateTime? dateto)
        {
            if (Session["Admin"] != null)
            {

                var od = db.OrderDetails;
                Session["DateFrom"] = datefrom;
                Session["DateTo"] = dateto;
                var order = db.OrderDetails.Include(x => x.Product).Include(x => x.Order).ToList();
                return View(order.Where(x => x.Order.Order_Date <= dateto  && x.Order.Order_Date >= datefrom).ToList());
               
            }
            return RedirectToAction("Login", "HomeAdmin");
        }
        public void ExportReportByDay()
        {
            var order = db.OrderDetails.Include(x => x.Product).Include(x => x.Order).ToList();
            var check = order.Where(x => x.Order.Order_Date.Date == DateTime.Now.Date);
           var sumquantity = check.Sum(x => x.Quantity);
            var sumtotal = check.Sum(x => x.Quantity * (x.Product.Product_Price - ((x.Product.Product_Price * x.Product.Product_Discount) / 100)));
           List<OrderViewModel> emplist = (order.Where(x => x.Order.Order_Date.Date == DateTime.Now.Date)).ToList().Select(x => new OrderViewModel
            {
               
                ID = x.Order_ID,
                 Product_ID = x.Product.Product_ID,
                Price = x.Product.Product_Price - ((x.Product.Product_Price *x.Product.Product_Discount)/100),
                Quantity = x.Quantity,
             Total = x.Quantity* (x.Product.Product_Price - ((x.Product.Product_Price * x.Product.Product_Discount) / 100)),
            Date = x.Order.Order_Date.ToString(),
         Customer_ID = x.Order.Customer.Customer_ID,
         QuantityTotal = sumquantity,
         SumTotal = sumtotal
           }).ToList();

            ExcelPackage pck = new ExcelPackage();
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Report");

            ws.Cells["A1"].Value = "Report orders by day";
             
            ws.Cells["A2"].Value = "Date export";
            ws.Cells["B2"].Value = string.Format("{0:dd MMMM yyyy} at {0:H: mm tt}", DateTimeOffset.Now);

            ws.Cells["A4"].Value = "Sum Quantity";
            ws.Cells["A5"].Value = "Sum Money";
            ws.Cells["B4"].Value = sumquantity;
            ws.Cells["B5"].Value = sumtotal;

            ws.Cells["A7"].Value = "ID";
            ws.Cells["B7"].Value = "Product ID";
            ws.Cells["C7"].Value = "Price";
            ws.Cells["D7"].Value = "Quantity";
            ws.Cells["E7"].Value = "Total";
            ws.Cells["F7"].Value = "Date";
            ws.Cells["G7"].Value = "Customer ID";
            
            int rowStart = 8;
            foreach (var item in emplist)
            {
              

                ws.Cells[string.Format("A{0}", rowStart)].Value = item.ID;
                ws.Cells[string.Format("B{0}", rowStart)].Value = item.Product_ID;
                ws.Cells[string.Format("C{0}", rowStart)].Value = item.Price;
                ws.Cells[string.Format("D{0}", rowStart)].Value = item.Quantity;
                ws.Cells[string.Format("E{0}", rowStart)].Value = item.Total;
                ws.Cells[string.Format("F{0}", rowStart)].Value = item.Date;
                ws.Cells[string.Format("G{0}", rowStart)].Value = item.Customer_ID;
                
                rowStart++;
            }

            ws.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", string.Format("attachment; filename=Jordan_Shop_Report_By_Day{0}.xls", DateTime.Now));
            Response.BinaryWrite(pck.GetAsByteArray());
            Response.End();

        }

        public void ExportReportDate()
        {
            var order = db.OrderDetails.Include(x => x.Product).Include(x => x.Order).ToList();
            var session = Session["FromDate"].ToString();
           
            int sumquantity1 = order.Where(x => x.Order.Order_Date.Date.ToString() == session).Sum(x => x.Quantity);
            int sumtotal1 = order.Where(x => x.Order.Order_Date.Date.ToString() == session).Sum(x => x.Quantity * (x.Product.Product_Price - ((x.Product.Product_Price * x.Product.Product_Discount) / 100)));
            List<OrderViewModel> emplist = (order.Where(x => x.Order.Order_Date.Date.ToString() == session)).ToList().Select(x => new OrderViewModel
            {

                ID = x.Order_ID,
                Product_ID = x.Product.Product_ID,
                Price = x.Product.Product_Price - ((x.Product.Product_Price * x.Product.Product_Discount) / 100),
                Quantity = x.Quantity,
                Total = x.Quantity * (x.Product.Product_Price - ((x.Product.Product_Price * x.Product.Product_Discount) / 100)),
                Date = x.Order.Order_Date.ToString(),
                Customer_ID = x.Order.Customer.Customer_ID,
                QuantityTotal = sumquantity1,
                SumTotal = sumtotal1
            }).ToList();

            ExcelPackage pck = new ExcelPackage();
            ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Report");

            ws.Cells["A1"].Value = "Report orders by from day";

            ws.Cells["A2"].Value = "Date export";
            ws.Cells["B2"].Value = string.Format("{0:dd MMMM yyyy} at {0:H: mm tt}", DateTimeOffset.Now);

            ws.Cells["A4"].Value = "Sum Quantity";
            ws.Cells["A5"].Value = "Sum Money";
            ws.Cells["B4"].Value = sumquantity1;
            ws.Cells["B5"].Value = sumtotal1;

            ws.Cells["A7"].Value = "ID";
            ws.Cells["B7"].Value = "Product ID";
            ws.Cells["C7"].Value = "Price";
            ws.Cells["D7"].Value = "Quantity";
            ws.Cells["E7"].Value = "Total";
            ws.Cells["F7"].Value = "Date";
            ws.Cells["G7"].Value = "Customer ID";

            int rowStart = 8;
            foreach (var item in emplist)
            {


                ws.Cells[string.Format("A{0}", rowStart)].Value = item.ID;
                ws.Cells[string.Format("B{0}", rowStart)].Value = item.Product_ID;
                ws.Cells[string.Format("C{0}", rowStart)].Value = item.Price;
                ws.Cells[string.Format("D{0}", rowStart)].Value = item.Quantity;
                ws.Cells[string.Format("E{0}", rowStart)].Value = item.Total;
                ws.Cells[string.Format("F{0}", rowStart)].Value = item.Date;
                ws.Cells[string.Format("G{0}", rowStart)].Value = item.Customer_ID;

                rowStart++;
            }

            ws.Cells["A:AZ"].AutoFitColumns();
            Response.Clear();
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", string.Format("attachment; filename=Jordan_Shop_Report_Date{0}.xls", DateTime.Now));
            Response.BinaryWrite(pck.GetAsByteArray());
            Response.End();

        }

        public void ExportReportDateRange()
        {
            var order = db.OrderDetails.Include(x => x.Product).Include(x => x.Order).ToList();
            var session1 = Session["DateFrom"];
            var session2 = Session["DateTo"];

            int sumquantity1 = order.Where(x => x.Order.Order_Date.Date <= (DateTime)session2 && x.Order.Order_Date.Date >= (DateTime)session1).Sum(x => x.Quantity);
            int sumtotal1 = order.Where(x => x.Order.Order_Date.Date <= (DateTime)session2 && x.Order.Order_Date.Date >= (DateTime)session1).Sum(x => x.Quantity * (x.Product.Product_Price - ((x.Product.Product_Price * x.Product.Product_Discount) / 100)));
            List<OrderViewModel> emplist = (order.Where(x => x.Order.Order_Date.Date <= (DateTime)session2 && x.Order.Order_Date.Date >= (DateTime)session1)).ToList().Select(x => new OrderViewModel
            {

                ID = x.Order_ID,
                Product_ID = x.Product.Product_ID,
                Price = x.Product.Product_Price - ((x.Product.Product_Price * x.Product.Product_Discount) / 100),
                Quantity = x.Quantity,
                Total = x.Quantity * (x.Product.Product_Price - ((x.Product.Product_Price * x.Product.Product_Discount) / 100)),
                Date = x.Order.Order_Date.ToString(),
                Customer_ID = x.Order.Customer.Customer_ID,
                QuantityTotal = sumquantity1,
                SumTotal = sumtotal1
            }).ToList();

            ExcelPackage pck = new ExcelPackage();

WebApplication/Views/MReport/DateRange.cshtml
@model IEnumerable<WebApplication.Models.OrderDetail>
@{
    ViewBag.Title = "DateRange";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Report Management</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/HomeAdmin">Home</a></li>
                    <li><span>Report Management</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="~/Theme/assets/images/author/avatar.png" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">Welcome: @Session["Admin"]<i class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Logout","HomeAdmin")">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row">
        <!-- Dark table start -->
        <div class="col-12 mt-5">
            <div class="card">

                <div class="card-body">
                    @using (Html.BeginForm("DateRange", "MReport", FormMethod.Get))
                    {
                        <p style="font-size:20px">Date From:</p>
                        <input type="date" id="timeCheckIn" name="datefrom" class="form-control col-md-2" />

                        <p style="font-size:20px">Date To:</p>
                        <input type="date" id="timeCheckOut" name="dateto" class="form-control col-md-2" />
                        @*<i>Product:</i>
            <input type="text" value="All" name="product" class="form-control" />*@
                        @*@Html.DropDownList("pro_id", null, htmlAttributes: new { @class = "form-control" })*@
                        <br />
                        <input type="submit" value="Search" class="btn btn-danger" />
                    }
                    <br />
                    @if (@Session["DateFrom"] != null && Session["DateTo"] != null)
                    {
                        <p>Result search date: From <strong>@Session["DateFrom"]</strong> to <strong>@Session["DateTo"]</strong></p>
                        <br />

                        <p> @Html.ActionLink("Export to Excel", "ExportReportDateRange", "MReport", null, new { @class = "btn btn-warning" })</p>
                    }
                    <br />
                    <h4 class="header-title">Report Order (Date Range)</h4>
                    <div class="data-tables datatable-dark">

                        <table class="table" id="dataTable" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Product Name
                                    </th>
                                    <th>
                                        Price (Including discount)

                                    </th>
                                    <th>
                                        Quantity
                                    </th>
                                    <th>
                                        Total
                                    </th>

                                    <th>
                                        Order Date
                                    </th>
                                    <th>
                                        Customer
                                    </th>
                                </tr>
                            </thead>
                            <tfoot>

                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th>Quantity Total:</th>
                                    <th>@Model.Sum(x => x.Quantity)
                                    <th>Sum Money:</th>
                                    <th>$ @Model.Sum(x => (x.Product_Price - (x.Product_Price * x.Product_Discount) / 100) * x.Quantity)

                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach (var group in Model.GroupBy(d => new { cusid = d.Order.Customer.Customer_ID, cus = d.Order.Customer.Customer_Name, orid = d.Order.Order_ID, price = d.Product_Price, discount = d.Product_Discount, image = d.Product.Product_Image, proid = d.Product.Product_ID, name = d.Product.Product_Name, date = d.Order.Order_Date }))
                                {
                                    <tr>
                                        @{var price = group.Key.price - ((group.Key.price * group.Key.discount) / 100); }
                                        <td>@group.Key.orid</td>
                                        <td>
                                            <a href="~/Images/@group.Key.image" target="_blank"><img src="~/Images/@group.Key.image" width="100" /></a>
                                        </td>
                                        <td>
                                            @group.Key.name
                                            <p>ID:  <a href="/MProduct/Details/@group.Key.proid">@group.Key.proid</a></p>
                                        </td>
                                        <td>
                                            $ @price
                                        </td>
                                        <td>
                                            @group.Sum(x => x.Quantity)
                                        </td>
                                        <td>
                                            $ @group.Sum(x => x.Quantity * price)
                                        </td>
                                        <td>
                                            @group.Key.date
                                        </td>
                                        <td>
                                            <a href="/MCustomer/Details/@group.Key.cusid">@group.Key.cus</a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- Dark table end -->
    </div>
</div>
<h2></h2>

WebApplication/Views/MReport/FromDate.cshtml
@model IEnumerable<WebApplication.Models.OrderDetail>

@{
    ViewBag.Title = "FromDate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Report Management</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/HomeAdmin">Home</a></li>
                    <li><span>Report Management</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="~/Theme/assets/images/author/avatar.png" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">Welcome: @Session["Admin"]<i class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Logout","HomeAdmin")">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row">
        <!-- Dark table start -->
        <div class="col-12 mt-5">
            <div class="card">

                <div class="card-body">
                    @using (Html.BeginForm("FromDate", "MReport", FormMethod.Get))
                    {
                        <div><p style="font-size:20px">Date:</p><span> <input type="date" id="timeCheckIn" name="datefrom" class="form-control col-md-2" /></span> </div>

                        @*<i>Product:</i>
            <input type="text" value="All" name="pro_id" />*@
                        @*@Html.DropDownList("pro_id", null, htmlAttributes: new { @class = "form-control" })*@
                        <br />
                        <input type="submit" value="Search" class="btn btn-danger" />
                    }
                    <br />
                    @if (@Session["FromDate"] != null)
                    {
                        <p>Result search date: <strong>@Session["FromDate"]</strong></p>

                        <br />

                        <p> @Html.ActionLink("Export to Excel", "ExportReportDate", "MReport", null, new { @class = "btn btn-warning" })</p>
                        <br />
                    }
                    <h4 class="header-title">Report Order (Date)</h4>
                    <div class="data-tables datatable-dark">


                        <table class="table" id="dataTable" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Product Name
                                    </th>
                                    <th>
                                        Price (Including discount)
                                    </th>
                                    <th>
                                        Quantity
                                    </th>
                                    <th>
                                        Total
                                    </th>

                                    <th>
                                        Order Date
                                    </th>
                                    <th>
                                        Customer
                                    </th>
                                </tr>
                            </thead>
                            <tfoot>

                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th>Quantity Total:</th>
                                    <th>@Model.Sum(x => x.Quantity)
                                    <th>Sum Money:</th>
                                    <th>$ @Model.Sum(x => (x.Product_Price - (x.Product_Price * x.Product_Discount) / 100) * x.Quantity)

                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach (var group in Model.GroupBy(d => new { cusid = d.Order.Customer.Customer_ID, cus = d.Order.Customer.Customer_Name, orid = d.Order.Order_ID, price = d.Product_Price, discount = d.Product_Discount, image = d.Product.Product_Image, proid = d.Product.Product_ID, name = d.Product.Product_Name, date = d.Order.Order_Date }))
                                {
                                    <tr>
                                        @{var price = group.Key.price - ((group.Key.price * group.Key.discount) / 100); }
                                        <td>@group.Key.orid</td>
                                        <td>
                                            <a href="~/Images/@group.Key.image" target="_blank"><img src="~/Images/@group.Key.image" width="100" /></a>
                                        </td>
                                        <td>
                                            @group.Key.name
                                            <p>ID:  <a href="/MProduct/Details/@group.Key.proid">@group.Key.proid</a></p>
                                        </td>
                                        <td>
                                            $ @price
                                        </td>
                                        <td>
                                            @group.Sum(x => x.Quantity)
                                        </td>
                                        <td>
                                            $ @group.Sum(x => x.Quantity * price)
                                        </td>
                                        <td>
                                            @group.Key.date
                                        </td>
                                        <td>
                                            <a href="/MCustomer/Details/@group.Key.cusid">@group.Key.cus</a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- Dark table end -->
    </div>
</div>

WebApplication/Views/MReport/Index.cshtml
@model IEnumerable<WebApplication.Models.OrderDetail>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Report Management</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="/HomeAdmin">Home</a></li>
                    <li><span>Report Management</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            <div class="user-profile pull-right">
                <img class="avatar user-thumb" src="~/Theme/assets/images/author/avatar.png" alt="avatar">
                <h4 class="user-name dropdown-toggle" data-toggle="dropdown">Welcome: @Session["Admin"]<i class="fa fa-angle-down"></i></h4>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="@Url.Action("Logout","HomeAdmin")">Log Out</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row">
        <!-- Dark table start -->
        <div class="col-12 mt-5">
            <div class="card">

                <div class="card-body">

                    <p> @Html.ActionLink("Export to Excel", "ExportReportByDay", "MReport", null, new { @class = "btn btn-warning" })</p>
                    <br />
                    <h4 class="header-title">Report Order (Today)</h4>
                    <div class="data-tables datatable-dark">

                        <table class="table" id="dataTable" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Product Name
                                    </th>
                                    <th>
                                        Price (Including discount)
                                    </th>
                                    <th>
                                        Quantity
                                    </th>
                                    <th>
                                        Total
                                    </th>

                                    <th>
                                        Order Date
                                    </th>
                                    <th>
                                        Customer
                                    </th>
                                </tr>
                            </thead>
                            <tfoot>

                                <tr>
                                    <th></th>
                                    <th></th>
                                    <th>Quantity Total:</th>
                                    <th>@Model.Sum(x => x.Quantity)
                                    <th>Sum Money:</th>
                                    <th>$ @Model.Sum(x => (x.Product_Price - (x.Product_Price * x.Product_Discount) / 100) * x.Quantity)

                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach (var group in Model.GroupBy(d => new { cusid = d.Order.Customer.Customer_ID, cus = d.Order.Customer.Customer_Name, orid = d.Order.Order_ID, price = d.Product_Price, discount = d.Product_Discount, image = d.Product.Product_Image, proid = d.Product.Product_ID, name = d.Product.Product_Name, date = d.Order.Order_Date }))
                                {
                                    <tr>
                                        @{var price = group.Key.price - ((group.Key.price * group.Key.discount) / 100); }
                                        <td>@group.Key.orid</td>
                                        <td>
                                            <a href="~/Images/@group.Key.image" target="_blank"><img src="~/Images/@group.Key.image" width="100" /></a>
                                        </td>
                                        <td>
                                            @group.Key.name
                                            <p>ID:  <a href="/MProduct/Details/@group.Key.proid">@group.Key.proid</a></p>
                                        </td>
                                        <td>
                                            $ @price
                                        </td>
                                        <td>
                                            @group.Sum(x => x.Quantity)
                                        </td>
                                        <td>
                                            $ @group.Sum(x => x.Quantity * price)
                                        </td>
                                        <td>
                                            @group.Key.date
                                        </td>
                                        <td>
                                            <a href="/MCustomer/Details/@group.Key.cusid">@group.Key.cus</a>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- Dark table end -->
    </div>
</div>